name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: R_ Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
    - name: R_ Checkout
      uses: actions/checkout@master

    - name: R_ Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: R_ Sync S3
      run: |
        aws s3 sync . s3://pirmas3


